---
name: ⚒️ CI

on:
  pull_request: {}
  push:
    branches:
      - master

env:
  BUNDLE_WITHOUT: release

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Run linter
        run: bundle exec rake rubocop
  test:
    needs: rubocop
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "2.7"
          - ruby: "3.0"
          - ruby: "3.1"
            codecov: "yes"
          - ruby: "3.2"
          - ruby: "3.3"
    env:
      CODECOV: ${{ matrix.codecov }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run unit tests
        run: bundle exec rake spec
      - name: Run behavior tests
        run: bundle exec cucumber
        env:
          GIT_COMMITTER_NAME: 'Aruba'
          GIT_COMMITTER_EMAIL: 'aruba@example.com'
          GIT_AUTHOR_NAME: 'Aruba'
          GIT_AUTHOR_EMAIL: 'aruba@example.com'
      - name: Build gem
        run: gem build --strict --verbose *.gemspec
  tests:
    needs:
      - rubocop
      - test
    runs-on: ubuntu-latest
    name: Test suite
    steps:
      - run: echo Test suite completed
